version: '3.7'
services:
  workspace:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile

    environment:
      - REDIS_URI=redis://redis:6379
      - DB_BIND=postgresql+asyncpg://monty:monty@postgres:5432/monty
      - USE_FAKEREDIS=false
      - SNEKBOX_URL=http://snekbox:8060/

    volumes:
      - .:/workspaces/monty-python:cached

    command: /bin/sh -c "while sleep 1000; do :; done"
